//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int IDAdmin { get; set; }
        public string Account { get; set; }
        public string password { get; set; }
        public Nullable<int> permission { get; set; }
    }
}
