//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhTro
    {
        public int MaAnh { get; set; }
        public string Anh { get; set; }
        public int MaTro { get; set; }
    
        public virtual NhaTro NhaTro { get; set; }
    }
}
