//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public Nullable<System.DateTime> DateHide { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public Nullable<int> HostID { get; set; }
        public Nullable<int> MotelID { get; set; }
        public Nullable<int> CustomID { get; set; }
        public Nullable<decimal> Electric { get; set; }
        public Nullable<decimal> Water { get; set; }
        public Nullable<decimal> Priece { get; set; }
        public Nullable<decimal> Wifi { get; set; }
        public string Status { get; set; }
    
        public virtual custom custom { get; set; }
        public virtual Host Host { get; set; }
        public virtual motel motel { get; set; }
    }
}
