//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motel()
        {
            this.Contracts = new HashSet<Contract>();
            this.ImageMotels = new HashSet<ImageMotel>();
            this.Orders = new HashSet<Order>();
        }
    
        public int MotelID { get; set; }
        public decimal Price { get; set; }
        public int ID { get; set; }
        public int Acreage { get; set; }
        public string Address { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiledDate { get; set; }
        public string Status { get; set; }
        public int AreaID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int HostID { get; set; }
    
        public virtual area area { get; set; }
        public virtual CategoryMotel CategoryMotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Host Host { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageMotel> ImageMotels { get; set; }
        public virtual searchprice searchprice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
