//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTro()
        {
            this.AnhTroes = new HashSet<AnhTro>();
        }
    
        public int MaTro { get; set; }
        public decimal Gia { get; set; }
        public int IDTimGia { get; set; }
        public int DienTich { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayDang { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string TrangThai { get; set; }
        public int MaKhuVuc { get; set; }
        public int MaDanhMuc { get; set; }
        public string TieuDe { get; set; }
        public string ChiTiet { get; set; }
        public string Anh { get; set; }
        public int MaChuTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhTro> AnhTroes { get; set; }
        public virtual ChuTro ChuTro { get; set; }
        public virtual DanhMucTro DanhMucTro { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        public virtual TimTheoGia TimTheoGia { get; set; }
    }
}
