//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNhaTro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaTroEntities2 : DbContext
    {
        public NhaTroEntities2()
            : base("name=NhaTroEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<CategoryMotel> CategoryMotels { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<custom> customs { get; set; }
        public virtual DbSet<Host> Hosts { get; set; }
        public virtual DbSet<ImageMotel> ImageMotels { get; set; }
        public virtual DbSet<motel> motels { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<searchprice> searchprices { get; set; }
    }
}
